import random

class Python:
    beginner = {
        1: 'Write a python program to add int and float number',
        2: 'Write a Python program to print "Hello, World!"',
        3: 'Write a Python program to add two integers.',
        4: 'Write a Python program to multiply two floating-point numbers.',
        5: 'Write a Python program to find the remainder of two numbers.',
        6: 'Write a Python program to find the power of a number using ** operator.',
        7: 'Write a Python program to swap two variables.',
        8: 'Write a Python program to calculate the area of a circle given its radius.',
        9: 'Write a Python program to calculate the perimeter of a rectangle.',
        10: 'Write a Python program to find the average of three numbers.',
        11: 'Write a Python program to convert kilometers to miles.',
        12: 'Write a Python program to check if a number is positive, negative or zero.',
        13: 'Write a Python program to check if a number is even or odd.',
        14: 'Write a Python program to find the largest of three numbers.',
        15: 'Write a Python program to check if a year is a leap year.',
        16: 'Write a Python program to find the factorial of a number.',
        17: 'Write a Python program to generate the first N Fibonacci numbers.',
        18: 'Write a Python program to find the sum of natural numbers up to N.',
        19: 'Write a Python program to reverse a given string.',
        20: 'Write a Python program to count the number of vowels in a given string.',
        21: 'Write a Python program to count the number of words in a given sentence.',
        22: 'Write a Python program to create a list of integers from 1 to 10.',
        23: 'Write a Python program to find the maximum and minimum values in a list.',
        24: 'Write a Python program to find the sum of all elements in a list.',
        25: 'Write a Python program to remove duplicates from a list.',
        26: 'Write a Python program to check if a list is empty.',
        27: 'Write a Python program to concatenate two lists.',
        28: 'Write a Python program to add an element at the end of a list.',
        29: 'Write a Python program to insert an element at a specific position in a list.',
        30: 'Write a Python program to remove an element from a list.',
        31: 'Write a Python program to find the length of a list.',
        32: 'Write a Python program to create a tuple with different data types.',
        33: 'Write a Python program to find the length of a tuple.',
        34: 'Write a Python program to convert a tuple to a list.',
        35: 'Write a Python program to convert a list to a tuple.',
        36: 'Write a Python program to create a dictionary with key-value pairs.',
        37: 'Write a Python program to add a key-value pair to a dictionary.',
        38: 'Write a Python program to remove a key from a dictionary.',
        39: 'Write a Python program to get a list of all keys in a dictionary.',
        40: 'Write a Python program to get a list of all values in a dictionary.',
        41: 'Write a Python program to check if a key exists in a dictionary.',
        42: 'Write a Python program to merge two dictionaries.',
        43: 'Write a Python program to create a set and add elements to it.',
        44: 'Write a Python program to remove an element from a set.',
        45: 'Write a Python program to find the union of two sets.',
        46: 'Write a Python program to find the intersection of two sets.',
        47: 'Write a Python program to find the difference between two sets.',
        48: 'Write a Python program to check if a set is a subset of another set.',
        49: 'Write a Python program to find the length of a set.',
        50: 'Write a Python program to create a set from a list.',
        51: 'Write a Python program to create a list of squares of numbers from 1 to 10.',
        52: 'Write a Python program to create a list of even numbers from 1 to 20.',
        53: 'Write a Python program to create a list of odd numbers from 1 to 20.',
        54: 'Write a Python program to create a list of prime numbers up to 50.',
        55: 'Write a Python program to create a list of multiples of 3 up to 30.',
        56: 'Write a Python program to find the largest element in a list.',
        57: 'Write a Python program to find the smallest element in a list.',
        58: 'Write a Python program to sort a list in ascending order.',
        59: 'Write a Python program to sort a list in descending order.',
        60: 'Write a Python program to find the second largest element in a list.',
        61: 'Write a Python program to find the second smallest element in a list.',
        62: 'Write a Python program to find the sum of elements in a list using a for loop.',
        63: 'Write a Python program to find the product of elements in a list using a for loop.',
        64: 'Write a Python program to print each element in a list using a for loop.',
        65: 'Write a Python program to print each character in a string using a for loop.',
        66: 'Write a Python program to count the number of occurrences of a character in a string.',
        67: 'Write a Python program to find the first occurrence of a character in a string.',
        68: 'Write a Python program to find the last occurrence of a character in a string.',
        69: 'Write a Python program to replace all occurrences of a character in a string with another character.',
        70: 'Write a Python program to convert a string to uppercase.',
        71: 'Write a Python program to convert a string to lowercase.',
        72: 'Write a Python program to capitalize the first letter of each word in a string.',
        73: 'Write a Python program to reverse the words in a given string.',
        74: 'Write a Python program to find the length of a string.',
        75: 'Write a Python program to check if a string is a palindrome.',
        76: 'Write a Python program to count the number of digits in a string.',
        77: 'Write a Python program to count the number of letters in a string.',
        78: 'Write a Python program to count the number of spaces in a string.',
        79: 'Write a Python program to count the number of special characters in a string.',
        80: 'Write a Python program to remove all vowels from a given string.',
        81: 'Write a Python program to remove all consonants from a given string.',
        82: 'Write a Python program to find the sum of digits in a given string.',
        83: 'Write a Python program to replace all spaces in a string with a hyphen.',
        84: 'Write a Python program to count the number of occurrences of a word in a sentence.',
        85: 'Write a Python program to find the first occurrence of a word in a sentence.',
        86: 'Write a Python program to find the last occurrence of a word in a sentence.',
        87: 'Write a Python program to replace all occurrences of a word in a sentence with another word.',
        88: 'Write a Python program to find the length of a list.',
        89: 'Write a Python program to find the length of a tuple.',
        90: 'Write a Python program to find the length of a dictionary.',
        91: 'Write a Python program to find the length of a set.',
        92: 'Write a Python program to print the keys in a dictionary.',
        93: 'Write a Python program to print the values in a dictionary.',
        94: 'Write a Python program to print the key-value pairs in a dictionary.',
        95: 'Write a Python program to create a dictionary from two lists.',
        96: 'Write a Python program to create a dictionary with numbers as keys and their squares as values.',
        97: 'Write a Python program to create a dictionary with numbers as keys and their cubes as values.',
        98: 'Write a Python program to merge two lists into a dictionary.',
        99: 'Write a Python program to create a list of keys from a dictionary.',
        100: 'Write a Python program to create a list of values from a dictionary.',
        101: 'Write a Python program to create a dictionary with keys from a list and values set to zero.',
        102: 'Write a Python program to create a dictionary with keys from a list and values set to the length of the keys.',
        103: 'Write a Python program to create a dictionary with keys from a list and values set to the square of the keys.',
        104: 'Write a Python program to create a dictionary with keys from a list and values set to the cube of the keys.',
        105: 'Write a Python program to create a dictionary with keys from a list and values set to the reverse.'    
    }
    
    medium = {
        1: 'Write a Python program to implement a basic calculator (addition, subtraction, multiplication, division).',
        2: 'Write a Python program to sort a list of tuples based on the second element.',
        3: 'Write a Python program to remove duplicates from a list while maintaining the order.',
        4: 'Write a Python program to find the longest word in a list of words.',
        5: 'Write a Python program to implement a basic text editor with functionality to insert and delete characters.',
        6: 'Write a Python program to check if a string is an anagram of another string.',
        7: 'Write a Python program to find all the permutations of a given string.',
        8: 'Write a Python program to find the intersection of two lists.',
        9: 'Write a Python program to implement a stack using a list.',
        10: 'Write a Python program to implement a queue using a list.',
        11: 'Write a Python program to check if a given string is a valid palindrome (ignoring spaces, punctuation, and case).',
        12: 'Write a Python program to find the GCD (Greatest Common Divisor) of two numbers.',
        13: 'Write a Python program to find the LCM (Least Common Multiple) of two numbers.',
        14: 'Write a Python program to generate all possible combinations of a list.',
        15: 'Write a Python program to find the most frequent element in a list.',
        16: 'Write a Python program to merge two sorted lists into a single sorted list.',
        17: 'Write a Python program to implement a binary search algorithm.',
        18: 'Write a Python program to find all unique triplets in an array that sum up to zero.',
        19: 'Write a Python program to implement a simple linked list.',
        20: 'Write a Python program to detect and remove loops in a linked list.',
        21: 'Write a Python program to implement a basic hash table.',
        22: 'Write a Python program to calculate the nth Fibonacci number using dynamic programming.',
        23: 'Write a Python program to find the median of a list of numbers.',
        24: 'Write a Python program to sort a dictionary by its values.',
        25: 'Write a Python program to count the occurrences of each word in a given text.',
        26: 'Write a Python program to implement a priority queue.',
        27: 'Write a Python program to check if a given number is a power of two.',
        28: 'Write a Python program to flatten a nested list.',
        29: 'Write a Python program to generate the Pascal’s triangle up to a given number of rows.',
        30: 'Write a Python program to implement a depth-first search algorithm on a graph.',
        31: 'Write a Python program to implement a breadth-first search algorithm on a graph.',
        32: 'Write a Python program to perform matrix multiplication.',
        33: 'Write a Python program to transpose a matrix.',
        34: 'Write a Python program to check if two matrices are equal.',
        35: 'Write a Python program to find the shortest path in a grid.',
        36: 'Write a Python program to solve the N-Queens problem.',
        37: 'Write a Python program to find the longest increasing subsequence in a list.',
        38: 'Write a Python program to calculate the power set of a set.',
        39: 'Write a Python program to find the longest common subsequence between two strings.',
        40: 'Write a Python program to find all unique substrings of a given string.',
        41: 'Write a Python program to implement an LRU (Least Recently Used) cache.',
        42: 'Write a Python program to find the intersection of multiple sets.',
        43: 'Write a Python program to rotate a matrix by 90 degrees.',
        44: 'Write a Python program to check if a binary tree is balanced.',
        45: 'Write a Python program to convert a binary tree to a doubly linked list.',
        46: 'Write a Python program to implement a red-black tree.',
        47: 'Write a Python program to find the number of connected components in an undirected graph.',
        48: 'Write a Python program to implement a Bloom filter.',
        49: 'Write a Python program to solve the knapsack problem using dynamic programming.',
        50: 'Write a Python program to find the shortest path between two nodes in a graph.',
        51: 'Write a Python program to implement a trie (prefix tree).',
        52: 'Write a Python program to find the median of two sorted arrays.',
        53: 'Write a Python program to find the k smallest elements in an array.',
        54: 'Write a Python program to calculate the number of inversions in an array.',
        55: 'Write a Python program to perform quicksort on an array.',
        56: 'Write a Python program to perform mergesort on an array.',
        57: 'Write a Python program to find the maximum subarray sum using Kadane’s algorithm.',
        58: 'Write a Python program to perform binary search on a sorted list.',
        59: 'Write a Python program to find the longest palindromic substring in a given string.',
        60: 'Write a Python program to solve the Sudoku puzzle.',
        61: 'Write a Python program to implement a simple hash function.',
        62: 'Write a Python program to calculate the number of ways to climb stairs given the number of steps.',
        63: 'Write a Python program to implement a basic event-driven system.',
        64: 'Write a Python program to find the longest common prefix among a list of strings.',
        65: 'Write a Python program to calculate the edit distance between two strings.',
        66: 'Write a Python program to find all unique combinations of numbers that sum up to a target value.',
        67: 'Write a Python program to implement a basic neural network.',
        68: 'Write a Python program to generate a random graph with a given number of nodes and edges.',
        69: 'Write a Python program to implement the A* search algorithm.',
        70: 'Write a Python program to solve the traveling salesman problem.',
        71: 'Write a Python program to find all cycles in a directed graph.',
        72: 'Write a Python program to perform depth-first traversal on a graph.',
        73: 'Write a Python program to perform breadth-first traversal on a graph.',
        74: 'Write a Python program to calculate the similarity between two documents using cosine similarity.',
        75: 'Write a Python program to implement a simple recommender system.',
        76: 'Write a Python program to perform clustering on a dataset using K-means algorithm.',
        77: 'Write a Python program to implement a basic decision tree classifier.',
        78: 'Write a Python program to create a basic simulation of a real-world problem (e.g., traffic system).',
        79: 'Write a Python program to perform linear regression on a dataset.',
        80: 'Write a Python program to find the maximum product of three integers in an array.',
        81: 'Write a Python program to solve the subset sum problem using dynamic programming.',
        82: 'Write a Python program to implement a basic genetic algorithm.',
        83: 'Write a Python program to solve the coin change problem using dynamic programming.',
        84: 'Write a Python program to perform feature scaling on a dataset.',
        85: 'Write a Python program to implement a basic Bayesian classifier.',
        86: 'Write a Python program to implement a basic SVM (Support Vector Machine) classifier.',
        87: 'Write a Python program to find the longest path in a weighted graph.',
        88: 'Write a Python program to implement a basic text classification algorithm.',
        89: 'Write a Python program to perform dimensionality reduction using PCA (Principal Component Analysis).',
        90: 'Write a Python program to implement a basic Markov chain model.',
        91: 'Write a Python program to perform hierarchical clustering on a dataset.',
        92: 'Write a Python program to solve the minimum spanning tree problem using Kruskal’s algorithm.',
        93: 'Write a Python program to solve the minimum spanning tree problem using Prim’s algorithm.',
        94: 'Write a Python program to find all strongly connected components in a directed graph.',
        95: 'Write a Python program to solve the job scheduling problem with deadlines.',
        96: 'Write a Python program to perform anomaly detection on a dataset.',
        97: 'Write a Python program to implement a basic Monte Carlo simulation.',
        98: 'Write a Python program to find the longest sequence of consecutive numbers in an array.',
        99: 'Write a Python program to solve the knapsack problem using a greedy algorithm.',
        100: 'Write a Python program to implement a simple game (e.g., Tic-Tac-Toe) with an AI opponent.'
    }

    hard = {
        1: 'Write a Python program to solve the 8-Queens problem using backtracking.',
        2: 'Write a Python program to implement the A* (A-star) pathfinding algorithm.',
        3: 'Write a Python program to solve the Travelling Salesman Problem using dynamic programming.',
        4: 'Write a Python program to implement the Knuth-Morris-Pratt (KMP) string matching algorithm.',
        5: 'Write a Python program to solve the Longest Common Subsequence problem using dynamic programming.',
        6: 'Write a Python program to implement a Segment Tree for range queries and updates.',
        7: 'Write a Python program to solve the Maximum Subarray Sum problem using Kadane’s algorithm with modifications.',
        8: 'Write a Python program to implement a suffix array and use it to find all occurrences of a pattern in a text.',
        9: 'Write a Python program to solve the Minimum Spanning Tree problem using Kruskal’s algorithm with Union-Find.',
        10: 'Write a Python program to implement Prim’s algorithm for finding the Minimum Spanning Tree.',
        11: 'Write a Python program to implement the Ford-Fulkerson algorithm for computing the maximum flow in a flow network.',
        12: 'Write a Python program to solve the N-Queens problem using a constraint propagation technique.',
        13: 'Write a Python program to implement a Bloom Filter.',
        14: 'Write a Python program to find the Shortest Path in a graph using Dijkstra’s algorithm.',
        15: 'Write a Python program to find the longest increasing subsequence using binary search and dynamic programming.',
        16: 'Write a Python program to solve the 0/1 Knapsack problem using dynamic programming with space optimization.',
        17: 'Write a Python program to implement a B-Tree with insertion, deletion, and search operations.',
        18: 'Write a Python program to solve the Subset Sum problem using dynamic programming.',
        19: 'Write a Python program to implement the Rabin-Karp string matching algorithm.',
        20: 'Write a Python program to solve the Longest Common Prefix problem using a Trie data structure.',
        21: 'Write a Python program to implement a Red-Black Tree with insertion and deletion operations.',
        22: 'Write a Python program to solve the Traveling Salesman Problem using a genetic algorithm.',
        23: 'Write a Python program to find the maximum submatrix sum in a 2D array using Kadane’s algorithm.',
        24: 'Write a Python program to solve the Word Break Problem using dynamic programming.',
        25: 'Write a Python program to implement the Sieve of Eratosthenes to find all prime numbers up to N.',
        26: 'Write a Python program to solve the Balanced Parentheses problem using a stack.',
        27: 'Write a Python program to solve the Maximum Rectangle in a Histogram problem using a stack-based approach.',
        28: 'Write a Python program to implement a Priority Queue using a binary heap.',
        29: 'Write a Python program to solve the Maximum Flow problem using the Edmonds-Karp algorithm.',
        30: 'Write a Python program to solve the Convex Hull problem using Graham’s scan algorithm.',
        31: 'Write a Python program to find all strongly connected components in a directed graph using Tarjan’s algorithm.',
        32: 'Write a Python program to solve the Minimum Edit Distance problem using dynamic programming.',
        33: 'Write a Python program to solve the Maximum Bipartite Matching problem using the Hopcroft-Karp algorithm.',
        34: 'Write a Python program to implement a Segment Tree with lazy propagation for range updates.',
        35: 'Write a Python program to solve the Longest Palindromic Substring problem using dynamic programming.',
        36: 'Write a Python program to solve the Maximum Product Subarray problem using dynamic programming.',
        37: 'Write a Python program to implement a Disjoint Set (Union-Find) data structure with path compression and union by rank.',
        38: 'Write a Python program to solve the Knapsack problem with fractional weights using a greedy approach.',
        39: 'Write a Python program to solve the Minimum Cost Path problem in a grid with obstacles.',
        40: 'Write a Python program to implement the K-Means Clustering algorithm from scratch.',
        41: 'Write a Python program to solve the Maximum Sum Rectangle problem in a 2D matrix using dynamic programming.',
        42: 'Write a Python program to implement the Floyd-Warshall algorithm for finding all-pairs shortest paths in a graph.',
        43: 'Write a Python program to solve the 0/1 Knapsack problem using branch and bound technique.',
        44: 'Write a Python program to solve the Minimum Path Sum problem in a grid using dynamic programming.',
        45: 'Write a Python program to solve the Sudoku puzzle using a constraint satisfaction approach.',
        46: 'Write a Python program to implement the Bit Manipulation techniques for common problems.',
        47: 'Write a Python program to solve the Maximum Matching in Bipartite Graph using augmenting paths.',
        48: 'Write a Python program to implement a Trie data structure with insertion, deletion, and search operations.',
        49: 'Write a Python program to solve the Largest Rectangle in Histogram problem using stack-based approach.',
        50: 'Write a Python program to solve the Maximum Sum of Non-Adjacent Elements problem using dynamic programming.',
        51: 'Write a Python program to implement a basic neural network from scratch.',
        52: 'Write a Python program to solve the Maximal Rectangle problem in a binary matrix using dynamic programming.',
        53: 'Write a Python program to implement the Fast Fourier Transform (FFT) algorithm.',
        54: 'Write a Python program to solve the Job Scheduling problem with deadlines and profits using dynamic programming.',
        55: 'Write a Python program to solve the Interval Scheduling Maximization problem using greedy algorithms.',
        56: 'Write a Python program to implement a Max-Heap data structure with insertion and deletion operations.',
        57: 'Write a Python program to solve the 8-Puzzle problem using the A* search algorithm.',
        58: 'Write a Python program to find the Kth largest element in an unsorted array using Quickselect algorithm.',
        59: 'Write a Python program to solve the Minimum Window Substring problem using sliding window technique.',
        60: 'Write a Python program to find the maximum value of a function over a given range using binary search.',
        61: 'Write a Python program to solve the Optimal Binary Search Tree problem using dynamic programming.',
        62: 'Write a Python program to implement the Cuckoo Hashing technique for collision resolution in hash tables.',
        63: 'Write a Python program to solve the Optimal Matrix Chain Multiplication problem using dynamic programming.',
        64: 'Write a Python program to solve the Maximum Product Subsequence problem using dynamic programming.',
        65: 'Write a Python program to solve the Maximum Sum Rectangle problem in a matrix with a given sum.',
        66: 'Write a Python program to find the minimum number of coins needed for a given amount using dynamic programming.',
        67: 'Write a Python program to solve the Maximum Product Subarray problem using divide and conquer approach.',
        68: 'Write a Python program to find all subsets of a given set using backtracking.',
        69: 'Write a Python program to solve the Maximum Sum of Increasing Subsequence problem using dynamic programming.',
        70: 'Write a Python program to solve the Weighted Interval Scheduling problem using dynamic programming.',
        71: 'Write a Python program to implement the Hopcroft-Karp algorithm for finding maximum matching in bipartite graphs.',
        72: 'Write a Python program to find the maximum sum subarray with at least one element using dynamic programming.',
        73: 'Write a Python program to solve the Traveling Salesman Problem using dynamic programming with memoization.',
        74: 'Write a Python program to find the longest common substring between two strings using dynamic programming.',
        75: 'Write a Python program to solve the Longest Common Substring problem using suffix arrays.',
        76: 'Write a Python program to implement the Discrete Fourier Transform (DFT) algorithm.',
        77: 'Write a Python program to find the longest sequence of consecutive elements in an unsorted array.',
        78: 'Write a Python program to solve the Minimum Cost Flow problem in a network using linear programming.',
        79: 'Write a Python program to find the Kth smallest element in a matrix sorted row-wise and column-wise.',
        80: 'Write a Python program to implement the Graham Scan algorithm for finding the convex hull of a set of points.',
        81: 'Write a Python program to solve the Maximum Independent Set problem using dynamic programming on trees.',
        82: 'Write a Python program to solve the Maximum Bipartite Matching problem using the Hungarian algorithm.',
        83: 'Write a Python program to solve the Minimum Vertex Cover problem using dynamic programming on trees.',
        84: 'Write a Python program to solve the Matrix Chain Multiplication problem using dynamic programming.',
        85: 'Write a Python program to implement a basic LRU cache with eviction policy.',
        86: 'Write a Python program to implement a basic B+ Tree with insertion and search operations.',
        87: 'Write a Python program to solve the Maximum Flow problem using the Dinic’s algorithm.',
        88: 'Write a Python program to solve the Longest Palindromic Subsequence problem using dynamic programming.',
        89: 'Write a Python program to solve the Maximum Matching in General Graphs using augmenting paths and DFS.',
        90: 'Write a Python program to solve the Subset Sum problem using a Meet in the Middle approach.',
        91: 'Write a Python program to implement a Graph with adjacency matrix and adjacency list representations.',
        92: 'Write a Python program to solve the Optimal Binary Search Tree problem using dynamic programming.',
        93: 'Write a Python program to solve the Maximum Sum Rectangle problem using Kadane’s algorithm in 2D.',
        94: 'Write a Python program to solve the Minimum Cost Path problem in a grid using Dijkstra’s algorithm.',
        95: 'Write a Python program to solve the Generalized N-Queens problem using constraint propagation.',
        96: 'Write a Python program to find the minimum number of swaps required to sort an array.',
        97: 'Write a Python program to solve the Maximum Flow problem using the Capacity Scaling algorithm.',
        98: 'Write a Python program to solve the Minimum Cost Perfect Matching problem using the Hungarian algorithm.',
        99: 'Write a Python program to find the maximum sum of elements in a matrix with the condition that no two elements are in the same row or column.',
        100: 'Write a Python program to implement a basic Quantum Annealing algorithm for optimization problems.'
    }


    @classmethod
    def get_questions(cls, num_questions_to_generate, level):
        if level == 'beginner':
            question_pool = cls.beginner
        elif level == 'medium':
            question_pool = cls.medium
        elif level == 'hard':
            question_pool = cls.hard
        else:
            print(f"Unsupported level: {level}")
            return {}

        selected_keys = random.sample(list(question_pool.keys()), k=num_questions_to_generate)
        selected_questions = {key: question_pool[key] for key in selected_keys}

        return selected_questions

def questions(num_questions_to_generate, level):
    return Python.get_questions(num_questions_to_generate, level)
